workaround to arg parse int
twitter/bazel-multiversion pull request #52
Opened 2021-03-18 23:37 UTC by wisechengyi

### Problem

```
$ java -Xmx10g -jar /Users/yic/workspace/multiversion/multiversion/target/scala-2.12/bazel-multiversion-assembly-0.1.0-SNAPSHOT.jar pants-export --output-path a.out --no-lint --cache /tmp/cache 3rdparty/jvm/:: --parallel 2
error: Type mismatch at '.parallel.save';
  found    : String
  expected : Int
```

2021-03-18 23:37 UTC, wisechengyi commented
@Duhemm please kindly comment if there is a better way to fix the issue.

2021-03-18 23:38 UTC, eed3si9n approved these changes

2021-03-19 08:18 UTC, Duhemm approved these changes
I think that's probably a bug in Moped. Thanks!

2021-03-19 08:24 UTC, Duhemm requested changes
Actually I think the correct fix is to import `moped.annotations.ParseAsNumber` and to annotate the parameter:

```scala
    @Description("Retry limit when fetching a file.")
    retryCount: Int = 2,
    @ParseAsNumber
    @Description("Number of parallel resolves and downloads.")
    parallel: Int = 4,
) extends Command {
  def app = lintCommand.app
  def run(): Int = {

```

2021-03-19 18:12 UTC, eed3si9n approved these changes

2021-03-19 18:12 UTC, merged